sudo: false
language: cpp
services:
  - docker
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ubuntu:disco; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo FROM ubuntu:disco > Dockerfile; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo ADD . /root >> Dockerfile; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "RUN echo 'deb [allow-insecure=yes] http://download.opensuse.org/repositories/home:/ptomato/xUbuntu_16.10/ /' > /etc/apt/sources.list.d/home:ptomato.list" >> Dockerfile; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo RUN apt-get update >> Dockerfile; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo RUN apt-get install --allow-unauthenticated -y meson ninja-build build-essential git pkg-config libglib2.0-dev gir1.2-glib-2.0 gobject-introspection libgirepository1.0-dev libmutter-4-dev jasmine-gjs >> Dockerfile; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t withgit .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run withgit /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX meson -Dwerror=true builddir && meson test -C builddir -v --num-processes=1"; fi

